# Generated by Django 6.0.4 on 2026-06-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_dibutuhkan', models.FloatField()),
                ('bahan_baku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bahanbaku')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep', to='core.menu')),
            ],
        ),
    ]
