# Generated by Django 6.0.4 on 2026-06-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resep'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanbaku',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
